### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by guilhermejcgois** [sollenne/ng4-fittext#1]
Hey guy, nice work with this library! You save our time at work... After merging the work of my colleague in our upstream repo, in my fork I update him and when I try to run our app after doing a `npm install` I've got the following error:

```
ERROR in Error encountered resolving symbol values statically.
    Function calls are not supported.
    Consider replacing the function or lambda with a reference to an exported 
function (position 194:50 in the original .ts file), resolving symbol NgModule in 
app/node_modules/ng4-fittext/node_modules/@angular/core/core.d.ts,
resolving symbol Ng4FittextModule in app/node_modules/ng4-fittext/src/ng4fittext.module.ts,
resolving symbol Ng4FittextModule in app/node_modules/ng4-fittext/src/ng4fittext.module.ts
```

I give a look at your package.json, and @angular/core isn't a peerDependency, do u have a strong reason to not to do this? I don't verify yet, but could be the root of the problem, someone can have that problem too.

Sorry for the bad title, best regards!

Gois

P.S.: strangely passed in our CI

**Comment by sollenne** [comment]
Let me take a look. What release are you using for this module? What's your NG4 version?

**Comment by sollenne** [comment]
@guilhermejcgois also are you using package.lock.json or yarn to lock down your dependencies?

**Comment by guilhermejcgois** [comment]
Hey @sollenne , sorry for the delay!

In our package,json, we have `"@angular/core": "^4.2.4"` and `"ng4-fittext": "^1.0.7"`. And when installing/updating the dependencies I got `UNMET PEER DEPENDENCY @angular/core@4.3.6`

**Comment by guilhermejcgois** [comment]
When removing node_modules directory and reinstalling all dependencies, the problem is over... :thinking:

**Comment by sollenne** [comment]
@guilhermejcgois . Cool. I think there was a dependency issue. I would recommend using Yarn so your app has all the angular versions for your dependencies. I would also update your angular version in package.json to the latest.
