### ISSUE TITLE
ng4-fittext usage issue

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [sollenne/ng4-fittext#4]
Hello,

I'm trying to use this for a project of mine.
I've already used the old fittext but that's not easy in angular.
The ng2 one has issues when I use it.
This one does not seem to work?

I've connected it to a div like this:

`<div class="information-input-2row" style="width:100px;color:black;background-color: rgba(0, 0, 0, 0.1);white-space: nowrap;" #base_1 [container]="base_1" [fittext] [activateOnResize]="true" [compression]="1.5">{{currentInfoModel?.base_1 | removeUndefined}}</div>`

The compression is done right of the bat when loading the component. However that's the only thing that happens.
No logic is done except for that.
The value of the text is loaded asynced, but the text is not resized anymore.
Also, when resizing the browser window nothing is done.

Any ideas?

Kind regards,

Lander

**Comment by sollenne** [comment]
the `[container]` attribute's value needs to be the parent container. So it should look like this.
```
<div #base_1 style="...">
    <div class="information-input-2row" 
            [container]="base_1" 
            [fittext] [activateOnResize]="true" 
            [compression]="1.5">
        {{currentInfoModel?.base_1 | removeUndefined}}
    </div>
</div>```

Hope this helps!

**Comment by LanderBeeuwsaert** [comment]
Hello Sollenne,

I tried it but that doesn't do the trick neither:

      ```
<div #top style="width:100%;display:flex;flex-direction: row"><!--class="full-flex-row" ;justify-content: flex-start"-->
        <div class="information-label" style="width: 50px">TOP</div>
        <div class="information-input-2row" style="width:100px;color:black;background-color: rgba(0, 0, 0, 0.1);white-space: nowrap;" [container]="top" [fittext] [activateOnResize]="true" [compression]="1.5">{{currentInfoModel?.top | removeUndefined}}</div>
      </div>
```

![image](https://user-images.githubusercontent.com/1098243/31188636-db78305e-a935-11e7-87b9-468553183bb8.png)

**Comment by LanderBeeuwsaert** [comment]
Thanks for the help!

**Comment by sollenne** [comment]
This is what happens when I test your snippet. 
What exactly is the problem?
If I had to guess. I would say that you don't have a width set on the parent container of the first `<div>` in your snippet. 

![recording 3](https://user-images.githubusercontent.com/2566489/31196149-4b8452a2-a912-11e7-9fb6-519a7ca7f5ea.gif)

**Comment by LanderBeeuwsaert** [comment]
![image](https://user-images.githubusercontent.com/1098243/31196999-f6019c98-a94f-11e7-86d4-7fc0d6315cdd.png)

Hello, I've put widths on 3 levels above the node I want to dynamically adapt. See the screenshot:
205px
-> 205px
-> -> 50px
-> -> 155 px

**Comment by sollenne** [comment]
Do you have a repo or plunkr? If not, can you paste a code snippet?

**Comment by LanderBeeuwsaert** [comment]
Ok, no problem.
Of course I can add a line of code to change the compression depending on the string length unintelligently (not taking the container into account).
However adapting the font-size depending on the string length unintelligently I can do with 1 line of code myself.

In all the other fitText repositories I've seen the whole point of the fitText idea is that it fits the text automatically to the container right?

**Comment by sollenne** [comment]
Original fittext works the same way. [See this CodePen
](https://codepen.io/sollenne/pen/BwJwVJ)
Maybe you should change the UI to allow more than 155px. That's very little space for a long name. Fittext is for large text, not tiny text. If you want to try it out, just make a PR. I'll take a look at getting this to work. Closing this issue for now

**Comment by LanderBeeuwsaert** [comment]
Hey Sollenne,

Ah ok.
I was talking about for example the 'ModelToWatch' from https://github.com/lokenxo/ng2-fittext.
but no problem, thanks for looking into it.

greetz
