### ISSUE TITLE
ng4-fittext usage issue - part 2

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [sollenne/ng4-fittext#5]
Hello Sollenne,

(see also: https://github.com/sollenne/ng4-fittext/issues/4#issuecomment-334210914 )

I tried it but that doesn't do the trick neither:

 
```
<div #top style="width:100%;display:flex;flex-direction: row">
        <div class="information-label" style="width: 50px">TOP</div>
        <div class="information-input-2row" style="width:100px;color:black;background-color: rgba(0, 0, 0, 0.1);white-space: nowrap;" [container]="top" [fittext] [activateOnResize]="true" [compression]="1.5">{{currentInfoModel?.top | removeUndefined}}</div>
</div>
```

![image](https://user-images.githubusercontent.com/1098243/31188636-db78305e-a935-11e7-87b9-468553183bb8.png)

**Comment by sollenne** [comment]
Closing this as duplicate to #4 ... Will reopen #4 to help.
