### ISSUE TITLE
Cannot read property 'clientWidth' of undefined

### ISSUE THREAD

**Issue by Jordan4jc** [sollenne/ng4-fittext#6]
I'm getting this error when trying to use this component. I thought at first it was because the containing div wasn't quite ready, or the content wasn't fully injected into the view so I tried a various number of timeouts and such but I still get the error.

If it helps here is my markup

    <div class="column right-column" *ngIf="style.width === 100">
      <div class="event-title">
        {{displayController.event.auction_title}}
      </div>
      <div class="amount" [fittext] [activateOnResize]="true" [container]="right-column">
        {{moduleProps.totals | values | sum | currency:'USD':true:'1.0-0'}}
      </div>
      <div class="text">Amount Raised</div>
    </div>

**Comment by sollenne** [comment]
Looks like the `[container]` value is `right-column`, but it's not set on the parent anywhere.
Try something like this

```
<div class="column right-column" #fittextParent>
    <div class="event-title">...</div>
    <div class="amount"
         [fittext]
         [container]="fittextParent">
        FittextString
    </div>
    <div class="text">...</div>
</div>
```

**Comment by Jordan4jc** [comment]
Trying this is throwing this error

```
Uncaught Error: Template parse errors:
Parser Error: Unexpected token # at column 2 in [ #fittextParent] in ng:///AppModule/TemplateModuleComponent.html@122:60 ("roller.event.auction_title}}
```

**Comment by sollenne** [comment]
@Jordan4jc do you have a repo I could look at?

**Comment by Jordan4jc** [comment]
I don't have a public repo, I can make it public temporarily or invite you.

Also, the template is not being generated in the `.ts` file, it's in the actual `.html` file

**Comment by sollenne** [comment]
You can give me access temporarily. I wouldn't want you to put it public.  
just email me rich@sollenne.com

**Comment by sollenne** [comment]
@Jordan4jc what happens when you paste my snippet into your code?

The error... specifically `[ #fittextParent]` makes me think it's still incorrect.

**Comment by Jordan4jc** [comment]
With that I get

```
Uncaught Error: Template parse errors:
Can't bind to '#fittextParent' since it isn't a known property of 'div'
```

**Comment by sollenne** [comment]
ok. in your `app.module.ts`, do you have `CUSTOM_ELEMENTS_SCHEMA` in your `schemas:`?

**Comment by Jordan4jc** [comment]
I added this and still get the `isn't a known property` error

**Comment by sollenne** [comment]
did you find a solution that worked for you @Jordan4jc?
