### ISSUE TITLE
Repository not synced with npm registry

### ISSUE THREAD

**Issue by guilhermejcgois** [sollenne/ng4-fittext#9]
One question, it's me or the repo isn't synced with npm registry? Here the last release is 1.0.6, but 1.1.4 in the npm... Also, the last version published in NPM broke our CI, we were able to start the build soon after it was published LOL

The error was `ERROR in Error: Metadata version mismatch for module /home/rof/.../node_modules/ng4-fittext/node_modules/@angular/core/core.d.ts, found version 4, expected 3, resolving symbol Ng4FittextModule in /home/rof/.../node_modules/ng4-fittext/ng4-fittext.d.ts, resolving symbol Ng4FittextModule in /home/rof/.../node_modules/ng4-fittext/ng4-fittext.d.ts`

**Comment by sollenne** [comment]
@guilhermejcgois... I was actually working on it right then (issue #8).
Everything should be synced now. 

Sorry for the timing.

**Comment by guilhermejcgois** [comment]
No problem man! Our trainee was a little annoyed because he had fixed some tests that he broke, but we already bought an ice cream for him and everything is fine! BTW, we'll wait for your fix to run again our pipeline before lock the version, thanks for this awesome lib! 😃
